### ISSUE TITLE
Issue while pip install

### ISSUE THREAD

**Issue by josete89** [pyscaffold/pyscaffoldext-custom-extension#27]
Whenever I install this package I get the following from pip
```
Installing collected packages: configupdater, pyscaffold, pyscaffoldext-custom-extension
  Attempting uninstall: configupdater
    Found existing installation: ConfigUpdater 2.0
    Uninstalling ConfigUpdater-2.0:
      Successfully uninstalled ConfigUpdater-2.0
  Attempting uninstall: pyscaffold
    Found existing installation: PyScaffold 4.0.1
    Uninstalling PyScaffold-4.0.1:
      Successfully uninstalled PyScaffold-4.0.1
Successfully installed configupdater-1.1.3 pyscaffold-4.0 pyscaffoldext-custom-extension-0.6.1
```
Seems to uninstall the latest version from PyScaffold and then putup command is not working any more: 
```
putup --a-python-template test                                                                                                                                                                  
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/bin/putup", line 5, in <module>
    from pyscaffold.cli import run
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/cli.py", line 13, in <module>
    from . import api, templates
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/api.py", line 9, in <module>
    from . import actions, info
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/actions.py", line 20, in <module>
    from . import info, repo
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/info.py", line 30, in <module>
    from .templates import ScaffoldOpts, licenses, parse_extensions
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/templates/__init__.py", line 14, in <module>
    from .. import dependencies as deps
  File "/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/pyscaffold/dependencies.py", line 9, in <module>
    from setuptools_scm.version import VERSION_CLASS
ImportError: cannot import name 'VERSION_CLASS' from 'setuptools_scm.version' (/usr/local/Caskroom/miniconda/base/envs/ds-template/lib/python3.8/site-packages/setuptools_scm/version.py)
```

I guess should be as easy as increase the requirements.
Cheers

**Comment by FlorianWilhelm** [comment]
Thanks for posting this issue. This should be resolved with the release of 0.6.2. Could you check, please?

**Comment by FlorianWilhelm** [comment]
@josete89 Any update on this?

**Comment by josete89** [comment]
Works as expected now
