### ISSUE TITLE
tox 4.0.17+ breaks test_custom_extension on windows

### ISSUE THREAD

**Issue by markferry** [pyscaffold/pyscaffoldext-custom-extension#69]
First mentioned here: https://github.com/tox-dev/tox/pull/2776#issuecomment-1396099200

tox 4.0.17 (specifically https://github.com/tox-dev/tox/commit/bf87bea75f2becbbcb29346567e6bf249da2b063) reliably breaks our custom extension built with Jenkins on Windows (python 3.8).

I bisected `tox` all the way between 4.0.16 (which was good) and 4.3.5.
No code changed and no python deps changed apart from tox.

**Log from `tox==4.3.5`:**
```
tmpfolder = WindowsPath('C:/Users/zSvcbuildmaster01/AppData/Local/Temp/pytest-of-unknown/pytest-99/test_generated_extension0/tmpqbuyf27f')

...
Error while running command:
['D:\\\\jenkins\\\\workspace\\\\pyscaffoldext-mything_master\\\\.tox\\\\test-windows\\\\Scripts\\\\python.EXE', '-m', 'tox']
{'stderr': -2, 'universal_newlines': True}

test-windows: internal error
Traceback (most recent call last):
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\session\\cmd\\run\\single.py", line 45, in _evaluate
    tox_env.setup()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\tox_env\\api.py", line 248, in setup
    self._setup_env()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\tox_env\\python\\runner.py", line 106, in _setup_env
    super()._setup_env()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\tox_env\\python\\api.py", line 198, in _setup_env
    self.ensure_python_env()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\tox_env\\python\\api.py", line 205, in ensure_python_env
    self.create_python_env()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\tox\\tox_env\\python\\virtual_env\\api.py", line 129, in create_python_env
    self.session.run()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\run\\session.py", line 42, in run
    self._create()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\run\\session.py", line 49, in _create
    self.creator.run()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\create\\creator.py", line 153, in run
    self.create()
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\create\\via_global_ref\\builtin\\via_global_self_do.py", line 89, in create
    src.run(self, self.symlinks)
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\create\\via_global_ref\\builtin\\ref.py", line 151, in run
    method(self.src, dest)
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\util\\path\\_sync.py", line 33, in copy
    ensure_safe_to_do(src, dest)
  File "D:\\jenkins\\workspace\\pyscaffoldext-mything_master\\.tox\\test-windows\\lib\\site-packages\\virtualenv\\util\\path\\_sync.py", line 23, in ensure_safe_to_do
    dest.unlink()
  File "C:\\Python38\\lib\\pathlib.py", line 1324, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 5] Access is denied: 'D:\\\\jenkins\\\\workspace\\\\pyscaffoldext-mything_master\\\\.tox\\\\test-windows\\\\Scripts\\\\python.exe'
test-windows: FAIL ! in 0.3 seconds

```

**Comment by markferry** [comment]
requirements.txt for the failed build:

```
alabaster==0.7.13
attrs==22.2.0
Babel==2.11.0
cachetools==5.2.1
certifi==2022.12.7
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.0.1
colorama==0.4.6
ConfigUpdater==3.1.1
coverage==7.0.5
distlib==0.3.6
docutils==0.19
exceptiongroup==1.1.0
execnet==1.9.0
filelock==3.9.0
identify==2.5.13
idna==3.4
imagesize==1.4.1
importlib-metadata==6.0.0
iniconfig==2.0.0
Jinja2==3.1.2
linkify-it-py==1.0.3
markdown-it-py==2.1.0
MarkupSafe==2.1.2
mdit-py-plugins==0.3.3
mdurl==0.1.2
myst-parser==0.18.1
nodeenv==1.7.0
packaging==23.0
platformdirs==2.6.2
pluggy==1.0.0
pre-commit==2.17.0
Pygments==2.14.0
pyproject_api==1.5.0
PyScaffold==4.3.1
pyscaffoldext-markdown==0.5
pytest==7.2.1
pytest-cov==4.0.0
pytest-xdist==3.1.0
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
setuptools-scm==7.1.0
snowballstemmer==2.2.0
Sphinx==5.3.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib.applehelp==1.0.3
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.6
tox==4.3.4
typing_extensions==4.4.0
uc-micro-py==1.0.1
urllib3==1.26.14
virtualenv==20.17.1
zipp==3.11.0
```

**Comment by markferry** [comment]
Can no longer reproduce this so going to assume it was something (environmental?) about the build host.
